# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "446b46ebb9d95fb182d5ac9566aa1f2b"
name = "pricer-sync-shahriar"
handle = "pricer-sync-shahriar-3"
application_url = "https://assist-pregnancy-pan-louisiana.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://assist-pregnancy-pan-louisiana.trycloudflare.com/auth/callback",
  "https://assist-pregnancy-pan-louisiana.trycloudflare.com/auth/shopify/callback",
  "https://assist-pregnancy-pan-louisiana.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
